In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Salary_Data.csv')

In [3]:
X = df.iloc[:, :-1].values

In [4]:
y = df.iloc[:, 1].values

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
sc_X = StandardScaler()

In [9]:
X_train = sc_X.fit_transform(X_train)

In [10]:
X_test = sc_X.transform(X_test)

In [21]:
y_train = y_train.reshape(-1,1)

In [23]:
y_test = y_test.reshape(-1,1)

In [24]:
y_train = sc_X.fit_transform(y_train)
y_test = sc_X.transform(y_test)

In [25]:
y_train

array([[-0.58893482],
       [-0.20450235],
       [-0.26937302],
       [-0.40591269],
       [ 1.75238875],
       [ 0.84837657],
       [-1.01636869],
       [ 2.08247565],
       [-0.44526921],
       [-1.27495041],
       [ 0.42348183],
       [ 0.93855664],
       [-0.56653314],
       [-0.67891012],
       [ 1.41533972],
       [-1.12612463],
       [-1.29739304],
       [ 1.11600906],
       [-0.12632172],
       [-0.5760344 ]])

In [26]:
y_test

array([[ 37731.],
       [122391.],
       [ 57081.],
       [ 63218.],
       [116969.],
       [109431.],
       [112635.],
       [ 55794.],
       [ 83088.],
       [101302.]])

In [27]:
from sklearn.linear_model import LinearRegression

In [28]:
lm = LinearRegression()

In [29]:
lm.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [30]:
pred = lm.predict(X_test)

In [31]:
y_test

array([[ 37731.],
       [122391.],
       [ 57081.],
       [ 63218.],
       [116969.],
       [109431.],
       [112635.],
       [ 55794.],
       [ 83088.],
       [101302.]])

In [32]:
pred

array([[-1.23628577],
       [ 2.13192314],
       [-0.24113314],
       [-0.31768334],
       [ 1.82572233],
       [ 1.51952152],
       [ 1.86399743],
       [-0.27940824],
       [ 0.21816808],
       [ 1.21332071]])